export const TEXTS = {
  common: {
    actions: 'Acciones',
    empty: 'No hay información disponible.',
    errorLoading: 'No fue posible cargar la información.',
    rowsPerPage: 'Filas por página',
  },
  users: {
    title: 'Usuarios',
    description: 'Administra los usuarios del sistema.',
    register: 'Registrar',
    empty: 'No hay usuarios registrados.',
    errorLoading: 'No fue posible cargar los usuarios.',
    delete: {
      title: 'Eliminar usuario',
      confirm: 'Sí, eliminar',
      success: 'Usuario eliminado correctamente.',
    },
    updatePage: {
      title: 'Editar usuario',
      description: 'Actualiza la información y los perfiles del usuario.',
      passwordHint: 'Por seguridad, confirma una contraseña de entre 12 y 128 caracteres.',
      cancel: 'Cancelar',
      submit: 'Guardar cambios',
      success: 'Usuario actualizado correctamente.',
      unexpectedError: 'No fue posible actualizar el usuario.',
      errorLoading: 'No fue posible cargar la información del usuario.',
    },
    registerPage: {
      title: 'Registro de usuario',
      description: 'Completa la información para registrar un nuevo usuario.',
      email: 'Correo electrónico',
      fullName: 'Nombre completo',
      password: 'Contraseña',
      passwordHint: 'Debe contener entre 12 y 128 caracteres.',
      profiles: 'Perfiles',
      profilesHint: 'Puedes seleccionar uno o varios perfiles.',
      cancel: 'Cancelar',
      submit: 'Registrar usuario',
      success: 'Usuario registrado correctamente.',
      unexpectedError: 'No fue posible registrar el usuario.',
    },
    columns: {
      number: 'No.',
      name: 'Nombre',
      email: 'Correo electrónico',
      profile: 'Perfil',
      verified: 'Verificado',
      status: 'Estado',
      created: 'Fecha de creación',
    },
  },
} as const
